application:
  institute: ICET
  batch: 104

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_reg
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update


